import React, { createContext, useContext, useState, useEffect, useCallback } from 'react';

type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations = {
  zh: {
    'app.title': 'FilmLog Pro',
    'app.new_record': '新建记录',
    'app.new': '新建',
    'app.selected_count': '已选择 {count} 项',
    'app.cancel': '取消',
    'app.bulk_delete': '批量删除',
    'app.loading': '正在加载数据...',
    'app.no_records': '未找到记录',
    'app.try_filter': '尝试调整搜索条件。',
    'app.start_record': '点击新建开始记录您的第一卷胶片。',
    'app.create_first': '创建第一条记录',
    'app.confirm_delete': '确认将这条记录移入回收站吗？',
    'app.confirm_bulk_delete': '确认删除选中的 {count} 条记录吗？',
    'app.bulk_delete_fail': '批量删除失败',
    'app.library': '冲洗工艺库',
    'app.settings': '设置',
    'app.trash': '回收站',
    'app.sync': '云端同步',
    'app.sync_success': '云端同步完成',
    'app.sync_fail': '同步失败，请检查网络设置',
    'app.auto_connected': '已自动连接至云端',
    'app.logout': '退出登录',

    'auth.login': '登录 FilmLog',
    'auth.register': '注册 FilmLog',
    'auth.login_desc': '使用邮箱和密码登录',
    'auth.register_desc': '创建新账户以同步您的数据',
    'auth.email': '邮箱',
    'auth.email_placeholder': '输入邮箱地址',
    'auth.password': '密码',
    'auth.password_placeholder': '输入密码',
    'auth.password_hint': '密码至少 6 位',
    'auth.submit_login': '登录',
    'auth.submit_register': '注册',
    'auth.processing': '处理中...',
    'auth.switch_to_register': '没有账户？立即注册',
    'auth.switch_to_login': '已有账户？去登录',
    'auth.register_success': '注册成功！请检查邮箱进行验证',
    'auth.error_credentials': '邮箱或密码错误',
    'auth.error_already_registered': '该邮箱已注册',
    'auth.error_password_length': '密码至少需要 6 位',
    'auth.error_invalid_email': '请输入有效的邮箱地址',
    'auth.username': '用户名',
    'auth.submit': '进入暗房',
    'auth.error': '用户名或密码错误',
    'auth.placeholder_user': '输入用户名',
    'auth.placeholder_pass': '输入密码',
    'auth.hint': '',

    'calc.title': '互易律失效计算器',
    'calc.tab_time': '计算曝光时间',
    'calc.tab_p': '反推 P 值',
    'calc.measured': '测光时间 (秒)',
    'calc.actual': '实际曝光 (秒)',
    'calc.nd_filter': 'ND 滤镜',
    'calc.nd_mode_factor': '倍率 (NDx)',
    'calc.nd_mode_stops': '档位 (+EV)',
    'calc.nd_hint': 'ND1(无), ND8, ND1000 等',
    'calc.nd_label': '滤镜后时间',
    'calc.factor': '失效系数 (P)',
    'calc.formula': '计算公式',
    'calc.formula_desc': '修正时间 = (测光 × ND) ^ P',
    'calc.formula_p_desc': 'P = ln(实际) / ln(测光)',
    'calc.result': '修正曝光时间',
    'calc.calculate': '计算',
    'calc.factor_hint': '请用户在官方文档中查询互易律失效数据，如实输入，予以计算。',
    'calc.threshold_label': '失效起始阈值 (秒)',
    'calc.threshold_hint': '在此时间之内无需修正 (参照组)',
    'calc.table_header_measured': 'T 测光',
    'calc.table_header_actual': 'T 实际',
    'calc.table_header_p': '单行 P 值',
    'calc.add_row': '添加数据组',
    'calc.avg_p': '平均 P 值',
    'calc.insufficient_data': '请至少输入一组有效数据 (测光 > 1s)',
    'calc.load_profile': '加载配置',
    'calc.save_profile': '保存配置',
    'calc.profile_name': '配置名称 (如胶片型号)',
    'calc.manage_profiles': '管理配置',
    'calc.no_profiles': '暂无保存的互易律配置',
    'calc.delete_profile': '删除配置',
    'calc.saved_success': '配置已保存',
    'calc.deleted_success': '配置已删除',
    'calc.mode_standard': '标准模式 (P值)',
    'calc.mode_advanced': '数学模型 (多项式)',
    'calc.coeff_a': '系数 a',
    'calc.coeff_b': '系数 b',
    'calc.coeff_c': '系数 c',
    'calc.formula_poly_desc': 'T = exp(a + b·ln(t_nd) + c·(ln(t_nd))²)',

    'settings.title': '应用设置',
    'settings.api_key': 'Gemini API 密钥',
    'settings.api_key_placeholder': '在此粘贴您的 API Key',
    'settings.api_key_hint': '密钥将存储在您的浏览器本地，不会上传到服务器。',
    'settings.save': '保存并刷新',
    'settings.saved': '设置已保存',
    'settings.get_key': '获取 API Key',
    'settings.cloud_title': '云端同步 (Supabase)',
    'settings.supabase_url': 'Project URL',
    'settings.supabase_key': 'Anon / Public Key',
    'settings.cloud_hint': '填写后支持手动同步至云端。清空则仅使用本地存储。',
    'settings.cloud_status_on': '● 准备就绪',
    'settings.cloud_status_off': '○ 仅本地存储',
    'settings.test_conn': '测试连接',
    'settings.testing': '正在测试...',
    'settings.test_success': '连接成功！',
    'settings.test_fail': '连接失败',
    'settings.menu_mode': '显示模式',
    'settings.mode_light': '明亮模式',
    'settings.mode_dark': '深色模式',
    'settings.mode_darkroom': '暗房模式 (红光)',
    'settings.menu_lang': '切换语言',

    'filter.search': '搜索记录',
    'filter.filter': '筛选',
    'filter.filter_count': '{count} 个筛选',
    'filter.add': '添加条件',
    'filter.no_active': '无活跃筛选条件。点击“添加条件”开始搜索。',
    'filter.contains': '包含',
    'filter.not_contains': '不包含',
    'filter.equals': '等于',
    'filter.not_equals': '不等于',
    'filter.placeholder': '输入内容...',

    'sort.label': '排序',
    'sort.date_desc': '日期 (最新)',
    'sort.date_asc': '日期 (最早)',
    'sort.model_asc': '型号 (A-Z)',
    'sort.model_desc': '型号 (Z-A)',

    'card.no_location_preview': '无地点预览',
    'card.edit': '编辑',
    'card.delete': '删除',
    'card.unknown_location': '未知地点',
    'card.dev': '冲洗',
    'card.unknown_chem': '未知药水',
    'card.stock': '原液',
    'card.dev_time': '显影',
    'card.fix_time': '定影',
    'card.preview': '成片预览',

    'editor.edit_title': '编辑记录',
    'editor.new_title': '新建胶片记录',
    'editor.tab_shooting': '拍摄信息',
    'editor.tab_developing': '冲洗信息',
    'editor.preview_location': '地点预览图',
    'editor.preview_film': '胶片预览图',
    'editor.upload': '点击上传',
    'editor.upload_hint': '支持 PNG, JPG, GIF 最大 5MB',
    'editor.upload_hint_film': '扫描件或照片',
    'editor.cancel': '取消',
    'editor.update': '更新记录',
    'editor.save_upload': '上传至云盘',
    'editor.save_fail': '保存失败',
    'editor.prewet': '是否预湿',
    'editor.load_recipe': '选择冲洗工艺',
    'editor.recipe_placeholder': '选择一个预设工艺自动填充...',
    'editor.ai_magic': 'AI 灵感',
    'editor.ai_generating': '思考中...',
    'editor.ai_error_no_key': '请先在右上角设置中配置 API Key',

    'timer.title': '冲洗助手',
    'timer.setup': '流程设置',
    'timer.start': '开始冲洗',
    'timer.reset': '重置',
    'timer.pause': '暂停',
    'timer.resume': '继续',
    'timer.skip': '跳过当前',
    'timer.finish': '完成',
    'timer.close': '关闭',
    'timer.sec': '秒',
    'timer.min': '分',
    'timer.total_time': '总时长',
    'timer.next_phase': '下一步',
    'timer.step_progress': '第 {current} 步 / 共 {total} 步',
    'timer.back': '上一步',
    'timer.next': '下一步',
    'timer.stages': '显影流程',
    'timer.add_stage': '添加阶段',
    'timer.stage_name': '药剂名称',
    'timer.dev_liquid_name': '显影液型号',
    'timer.fix_liquid_name': '定影液型号',
    'timer.prewet_agent_name': '预湿剂型号',
    'timer.stage_dilution': '浓度/比例',
    'timer.stage_default_name': '药液',
    'timer.volume_ml': '体积(ml)',
    'timer.duration': '时长',
    'timer.loop_count': '循环次数',
    'timer.loop_desc': '将上述阶段组合重复 {count} 次',
    'timer.global_settings': '全局设置',
    'timer.add_step': '添加显影步骤',
    'timer.add_developer': '添加显影液',
    'timer.step_name': '步骤名称',
    'timer.duration_label': '时长',
    'timer.phase_prewet': '预湿',
    'timer.phase_develop': '显影',
    'timer.phase_stop': '停显',
    'timer.phase_fix': '定影',
    'timer.phase_wash': '水洗',
    'timer.phase_wait': '倒药/等待',
    'timer.enable_wait': '启用倒药等待阶段',
    'timer.wait_time': '等待时长',
    'timer.agitation_settings': '摇晃设置',
    'timer.initial_agitation': '初始',
    'timer.agitation_duration': '摇晃',
    'timer.stand_duration': '静置',
    'timer.alert_agitate': '开始摇晃!',
    'timer.alert_stand': '静置',
    'timer.alert_pre_agitate': '准备摇晃...',
    'timer.remaining': '剩余 {time}',
    'timer.alert_next': '下一步: {phase}',
    'timer.finished_msg': '冲洗流程结束！',
    'timer.wetting_agent': '去水渍药剂',
    'timer.stop_agent': '停显剂',
    'timer.process_name': '工艺名称',
    'timer.save_process': '保存工艺',
    'timer.select_process': '选择工艺',
    'timer.film_model': '胶片型号',
    'timer.save_short': '保存',
    'timer.select_short': '选择',
    'timer.section_recipe': '工艺与配方',
    'timer.section_dev': '显影阶段',
    'timer.section_stop': '停显阶段',
    'timer.section_fix': '定影阶段',
    'timer.section_wash': '水洗阶段',
    'timer.enable_agent': '使用{name}',
    'timer.agent_name': '药剂名称',
    'timer.fixer_model': '定影液',
    'timer.saved_success': '工艺已保存！',
    'timer.select_modal_title': '选择预设工艺',
    'timer.est_cycles': '预计摇晃 {count} 次',
    'timer.loop_dev_steps': '显影序列循环次数',
    'timer.global_agitation': '全局摇晃设置',
    'timer.global_agitation_enable': '启用全局摇晃设置',
    'timer.separate_setting': '独立设定摇晃与倒药参数',
    'timer.using_global': '正在使用全局设置',
    'timer.timeline_overview': '冲洗时间轴预览',
    'timer.process_map': '冲洗流程图',
    'timer.cycle_label': '每 {time}s 循环',
    'timer.info_tip': '提示',
    'timer.custom_pour': '独立倒药/等待时长',
    'timer.skip_initial_loop': '仅首次循环进行初始摇晃',

    'library.title': '冲洗工艺库',
    'library.empty': '暂无保存的冲洗工艺',
    'library.overview': '概览',
    'library.details': '详情',
    'library.notes': '备注',
    'library.notes_placeholder': '输入关于此工艺的备注...',
    'library.save_notes': '保存备注',
    'library.total_time': '总耗时',
    'library.steps': '步骤数',
    'library.temp': '温度',
    'library.delete': '删除工艺',
    'library.confirm_delete': '确定删除此工艺吗？',
    'library.new_process': '新建工艺',
    'library.edit_process': '编辑工艺',
    'library.close': '关闭库',

    'trash.title': '回收站',
    'trash.empty': '回收站是空的',
    'trash.restore': '恢复',
    'trash.delete_forever': '彻底删除',
    'trash.confirm_permanent': '确定要永久删除这条记录吗？此操作不可撤销。',
    'trash.clear_all': '清空回收站',

    'field.filmModel': '胶片型号',
    'field.format': '画幅',
    'field.date': '拍摄时间',
    'field.location': '拍摄地点',
    'field.aperture': '光圈',
    'field.shutterSpeed': '快门速度',
    'field.flashPower': '闪光灯功率',
    'field.devMethod': '冲洗方式',
    'field.developerModel': '显影药型号',
    'field.devProcess': '冲洗工艺',
    'field.devDilution': '显影浓度',
    'field.devTime': '显影时间',
    'field.fixerModel': '定影液型号',
    'field.fixDilution': '定影浓度',
    'field.fixTime': '定影时间',
    'field.shootingNotes': '拍摄备注',
    'field.devNotes': '冲洗备注',

    'enum.Hand': '手冲',
    'enum.Rotary': '滚冲',
    'enum.Machine': '机洗',
    'enum.Tray': '显影盘',
    'enum.Stand': '静置/立冲',
    
    'placeholder.filmModel': '例如：Kodak Gold 200',
    'placeholder.location': '例如：上海，外滩',
    'placeholder.aperture': '例如：f/2.8',
    'placeholder.shutterSpeed': '例如：1/125',
    'placeholder.flashPower': '例如：1/16, TTL',
    'placeholder.devProcess': '例如：C-41, BW',
    'placeholder.developerModel': '例如：显影液型号',
    'placeholder.devDilution': '例如：1:19, 1:4',
    'placeholder.devTime': '例如：6:30',
    'placeholder.fixerModel': '例如：定影液型号',
    'placeholder.fixDilution': '例如：1:4, 1:9',
    'placeholder.fixTime': '例如：5:00',
    'placeholder.agent_name': '例如：Kodak Photo-Flo',
    'placeholder.stop_agent': '例如：Kodak Indicator Stop Bath',
    'placeholder.process_name': '例如：Kodak T-Max 400 推两档',
  },
  en: {
    'app.title': 'FilmLog Pro',
    'app.new_record': 'New Record',
    'app.new': 'New',
    'app.selected_count': '{count} Selected',
    'app.cancel': 'Cancel',
    'app.bulk_delete': 'Delete All',
    'app.loading': 'Loading data...',
    'app.no_records': 'No records found',
    'app.try_filter': 'Try adjusting your search filters.',
    'app.start_record': 'Click New to log your first roll.',
    'app.create_first': 'Create First Record',
    'app.confirm_delete': 'Move this record to Trash?',
    'app.confirm_bulk_delete': 'Are you sure you want to delete {count} records?',
    'app.bulk_delete_fail': 'Bulk delete failed',
    'app.library': 'Process Library',
    'app.settings': 'Settings',
    'app.trash': 'Trash Bin',
    'app.sync': 'Cloud Sync',
    'app.sync_success': 'Sync Complete',
    'app.sync_fail': 'Sync failed, check connection',
    'app.auto_connected': 'Connected to Cloud',
    'app.logout': 'Sign Out',

    'auth.login': 'Login to FilmLog',
    'auth.register': 'Register for FilmLog',
    'auth.login_desc': 'Sign in with your email and password',
    'auth.register_desc': 'Create an account to sync your data',
    'auth.email': 'Email',
    'auth.email_placeholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.password_placeholder': 'Enter your password',
    'auth.password_hint': 'At least 6 characters',
    'auth.submit_login': 'Sign In',
    'auth.submit_register': 'Sign Up',
    'auth.processing': 'Processing...',
    'auth.switch_to_register': "Don't have an account? Register",
    'auth.switch_to_login': 'Already have an account? Sign in',
    'auth.register_success': 'Registration successful! Please check your email to verify.',
    'auth.error_credentials': 'Invalid email or password',
    'auth.error_already_registered': 'This email is already registered',
    'auth.error_password_length': 'Password must be at least 6 characters',
    'auth.error_invalid_email': 'Please enter a valid email address',
    'auth.username': 'Username',
    'auth.submit': 'Enter Darkroom',
    'auth.error': 'Invalid credentials',
    'auth.placeholder_user': 'Username',
    'auth.placeholder_pass': 'Password',
    'auth.hint': '',

    'calc.title': 'Reciprocity Calc',
    'calc.tab_time': 'Calc Time',
    'calc.tab_p': 'Find P-Factor',
    'calc.measured': 'Measured Time (s)',
    'calc.actual': 'Actual Exposure (s)',
    'calc.nd_filter': 'ND Filter',
    'calc.nd_mode_factor': 'Factor (NDx)',
    'calc.nd_mode_stops': 'Stops (+EV)',
    'calc.nd_hint': 'ND1, ND8, ND1000 etc.',
    'calc.nd_label': 'Time after ND',
    'calc.factor': 'P-Factor',
    'calc.formula': 'Formula',
    'calc.formula_desc': 'Corrected = (Measured × ND) ^ P',
    'calc.formula_p_desc': 'P = ln(Actual) / ln(Measured)',
    'calc.result': 'Corrected Time',
    'calc.calculate': 'Calculate',
    'calc.factor_hint': 'Please query reciprocity failure data in the official documentation and enter it truthfully for calculation.',
    'calc.threshold_label': 'Failure Threshold (s)',
    'calc.threshold_hint': 'No correction needed below this (Reference)',
    'calc.table_header_measured': 'T Meter',
    'calc.table_header_actual': 'T Actual',
    'calc.table_header_p': 'Row P',
    'calc.add_row': 'Add Row',
    'calc.avg_p': 'Average P',
    'calc.insufficient_data': 'Enter valid data (Metered > 1s)',
    'calc.load_profile': 'Load Profile',
    'calc.save_profile': 'Save Profile',
    'calc.profile_name': 'Profile Name (e.g. Film Model)',
    'calc.manage_profiles': 'Manage Profiles',
    'calc.no_profiles': 'No saved reciprocity profiles',
    'calc.delete_profile': 'Delete Profile',
    'calc.saved_success': 'Profile Saved',
    'calc.deleted_success': 'Profile Deleted',
    'calc.mode_standard': 'Standard Mode (P-Factor)',
    'calc.mode_advanced': 'Math Model (Polynomial)',
    'calc.coeff_a': 'Coeff a',
    'calc.coeff_b': 'Coeff b',
    'calc.coeff_c': 'Coeff c',
    'calc.formula_poly_desc': 'T = exp(a + b·ln(t_nd) + c·(ln(t_nd))²)',

    'settings.title': 'Settings',
    'settings.api_key': 'Gemini API Key',
    'settings.api_key_placeholder': 'Paste your API Key here',
    'settings.api_key_hint': 'Your key is stored locally in your browser and is not sent to our servers.',
    'settings.save': 'Save & Reload',
    'settings.saved': 'Settings Saved',
    'settings.get_key': 'Get API Key',
    'settings.cloud_title': 'Cloud Sync (Supabase)',
    'settings.supabase_url': 'Project URL',
    'settings.supabase_key': 'Anon / Public Key',
    'settings.cloud_hint': 'Enables manual sync to cloud. Clear to use local storage only.',
    'settings.cloud_status_on': '● Ready to Sync',
    'settings.cloud_status_off': '○ Local Only',
    'settings.test_conn': 'Test Connection',
    'settings.testing': 'Testing...',
    'settings.test_success': 'Connection Successful!',
    'settings.test_fail': 'Connection Failed',
    'settings.menu_mode': 'Display Mode',
    'settings.mode_light': 'Light Mode',
    'settings.mode_dark': 'Dark Mode',
    'settings.mode_darkroom': 'Darkroom Mode (Red)',
    'settings.menu_lang': 'Language',

    'filter.search': 'Search',
    'filter.filter': 'Filter',
    'filter.filter_count': '{count} Filters',
    'filter.add': 'Add Condition',
    'filter.no_active': 'No active filters. Click "Add Condition" to start.',
    'filter.contains': 'Contains',
    'filter.not_contains': 'Not Contains',
    'filter.equals': 'Equals',
    'filter.not_equals': 'Not Equals',
    'filter.placeholder': 'Enter value...',

    'sort.label': 'Sort by',
    'sort.date_desc': 'Date (Newest)',
    'sort.date_asc': 'Date (Oldest)',
    'sort.model_asc': 'Model (A-Z)',
    'sort.model_desc': 'Model (Z-A)',

    'card.no_location_preview': 'No Preview',
    'card.edit': 'Edit',
    'card.delete': 'Delete',
    'card.unknown_location': 'Unknown Location',
    'card.dev': 'Dev',
    'card.unknown_chem': 'Unknown Chem',
    'card.stock': 'Stock',
    'card.dev_time': 'Dev',
    'card.fix_time': 'Fix',
    'card.preview': 'Photos',

    'editor.edit_title': 'Edit Record',
    'editor.new_title': 'New Film Record',
    'editor.tab_shooting': 'Shooting Info',
    'editor.tab_developing': 'Developing Info',
    'editor.preview_location': 'Location Preview',
    'editor.preview_film': 'Film Preview',
    'editor.upload': 'Upload',
    'editor.upload_hint': 'PNG, JPG, GIF max 5MB',
    'editor.upload_hint_film': 'Scans or Photos',
    'editor.cancel': 'Cancel',
    'editor.update': 'Update Record',
    'editor.save_upload': 'Save to Cloud',
    'editor.save_fail': 'Failed to save',
    'editor.prewet': 'Pre-wet',
    'editor.load_recipe': 'Load Recipe',
    'editor.recipe_placeholder': 'Select a recipe to autofill...',
    'editor.ai_magic': 'AI Magic',
    'editor.ai_generating': 'Thinking...',
    'editor.ai_error_no_key': 'Please configure API Key in Settings first',

    'timer.title': 'Dev Timer',
    'timer.setup': 'Setup Process',
    'timer.start': 'Start Timer',
    'timer.reset': 'Reset',
    'timer.pause': 'Pause',
    'timer.resume': 'Resume',
    'timer.skip': 'Skip',
    'timer.finish': 'Finish',
    'timer.close': 'Close',
    'timer.sec': 's',
    'timer.min': 'm',
    'timer.total_time': 'Total Time',
    'timer.next_phase': 'Next',
    'timer.step_progress': 'Step {current} of {total}',
    'timer.back': 'Back',
    'timer.next': 'Next',
    'timer.stages': 'Dev Process',
    'timer.add_stage': 'Add Stage',
    'timer.stage_name': 'Agent Name',
    'timer.dev_liquid_name': 'Dev Liquid',
    'timer.fix_liquid_name': 'Fixer Liquid',
    'timer.prewet_agent_name': 'Pre-wet Agent',
    'timer.stage_dilution': 'Dilution',
    'timer.stage_default_name': 'Stage',
    'timer.volume_ml': 'Vol (ml)',
    'timer.duration': 'Duration',
    'timer.loop_count': 'Loop Count',
    'timer.loop_desc': 'Repeat sequence {count} times',
    'timer.global_settings': 'Global Settings',
    'timer.add_step': 'Add Dev Step',
    'timer.add_developer': 'Add Developer',
    'timer.step_name': 'Name',
    'timer.duration_label': 'Duration',
    'timer.phase_prewet': 'Pre-wet',
    'timer.phase_develop': 'Developer',
    'timer.phase_stop': 'Stop Bath',
    'timer.phase_fix': 'Fixer',
    'timer.phase_wash': 'Wash',
    'timer.phase_wait': 'Pour / Wait',
    'timer.enable_wait': 'Enable Pour / Wait Phase',
    'timer.wait_time': 'Wait Duration',
    'timer.agitation_settings': 'Agitation',
    'timer.initial_agitation': 'Init',
    'timer.agitation_duration': 'Shake',
    'timer.stand_duration': 'Stand',
    'timer.alert_agitate': 'Shake!',
    'timer.alert_stand': 'Stand',
    'timer.alert_pre_agitate': 'Get Ready...',
    'timer.remaining': '{time}s left',
    'timer.alert_next': 'Next: {phase}',
    'timer.finished_msg': 'Process Complete!',
    'timer.wetting_agent': 'Wetting Agent',
    'timer.stop_agent': 'Stop Bath',
    'timer.process_name': 'Process Name',
    'timer.save_process': 'Save Process',
    'timer.select_process': 'Select Process',
    'timer.film_model': 'Film Model',
    'timer.save_short': 'Save',
    'timer.select_short': 'Select',
    'timer.section_recipe': 'Process & Recipe',
    'timer.section_dev': 'Development',
    'timer.section_stop': 'Stop Bath',
    'timer.section_fix': 'Fixing',
    'timer.section_wash': 'Washing',
    'timer.enable_agent': 'Use {name}',
    'timer.agent_name': 'Agent Name',
    'timer.fixer_model': 'Fixer',
    'timer.saved_success': 'Process Saved!',
    'timer.select_modal_title': 'Select Process Preset',
    'timer.est_cycles': 'Est. Cycles: {count}',
    'timer.loop_dev_steps': 'Loop Dev Sequence',
    'timer.global_agitation': 'Global Agitation Settings',
    'timer.global_agitation_enable': 'Enable Global Agitation',
    'timer.separate_setting': 'Separate Settings',
    'timer.using_global': 'Using Global Settings',
    'timer.timeline_overview': 'Process Timeline Preview',
    'timer.process_map': 'Process Map',
    'timer.cycle_label': 'Every {time}s',
    'timer.info_tip': 'Info',
    'timer.custom_pour': 'Independent Pour / Wait',
    'timer.skip_initial_loop': 'Initial Agitation only on first loop',

    'library.title': 'Process Library',
    'library.empty': 'No saved processes yet.',
    'library.overview': 'Overview',
    'library.details': 'Details',
    'library.notes': 'Notes',
    'library.notes_placeholder': 'Enter notes about this process...',
    'library.save_notes': 'Save Notes',
    'library.total_time': 'Total Time',
    'library.steps': 'Steps',
    'library.temp': 'Temp',
    'library.delete': 'Delete Process',
    'library.confirm_delete': 'Delete this process?',
    'library.new_process': 'New Process',
    'library.edit_process': 'Edit Process',
    'library.close': 'Close Library',

    'trash.title': 'Trash Bin',
    'trash.empty': 'Trash is empty',
    'trash.restore': 'Restore',
    'trash.delete_forever': 'Delete Forever',
    'trash.confirm_permanent': 'Permanently delete this record? This cannot be undone.',
    'trash.clear_all': 'Clear Trash',

    'field.filmModel': 'Film Model',
    'field.format': 'Format',
    'field.date': 'Date',
    'field.location': 'Location',
    'field.aperture': 'Aperture',
    'field.shutterSpeed': 'Shutter',
    'field.flashPower': 'Flash Power',
    'field.devMethod': 'Dev Method',
    'field.developerModel': 'Developer',
    'field.devProcess': 'Process',
    'field.devDilution': 'Dev Dilution',
    'field.devTime': 'Dev Time',
    'field.fixerModel': 'Fixer',
    'field.fixDilution': 'Fix Dilution',
    'field.fixTime': 'Fix Time',
    'field.shootingNotes': 'Shooting Notes',
    'field.devNotes': 'Developing Notes',

    'enum.Hand': 'Hand',
    'enum.Rotary': 'Rotary',
    'enum.Machine': 'Machine',
    'enum.Tray': 'Tray',
    'enum.Stand': 'Stand',
    
    'placeholder.filmModel': 'e.g., Kodak Gold 200',
    'placeholder.location': 'e.g., Shanghai, Bund',
    'placeholder.aperture': 'e.g., f/2.8',
    'placeholder.shutterSpeed': 'e.g., 1/125',
    'placeholder.flashPower': 'e.g., 1/16, TTL',
    'placeholder.devProcess': 'e.g., C-41, BW',
    'placeholder.developerModel': 'e.g., Developer Model',
    'placeholder.devDilution': 'e.g., 1:19, 1:4',
    'placeholder.devTime': 'e.g., 6:30',
    'placeholder.fixerModel': 'e.g., Fixer Model',
    'placeholder.fixDilution': 'e.g., 1:4, 1:9',
    'placeholder.fixTime': 'e.g., 5:00',
    'placeholder.agent_name': 'e.g., Kodak Photo-Flo',
    'placeholder.stop_agent': 'e.g., Kodak Indicator Stop Bath',
    'placeholder.process_name': 'e.g., Kodak T-Max 400 Push +2',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('filmlog_language');
    // Default to 'zh' if not set
    return (saved === 'en' || saved === 'zh') ? (saved as Language) : 'zh';
  });

  useEffect(() => {
    localStorage.setItem('filmlog_language', language);
  }, [language]);

  const t = useCallback((key: string, params?: Record<string, string | number>) => {
    const text = translations[language][key as keyof typeof translations['zh']] || key;
    if (params) {
      return Object.entries(params).reduce((acc, [k, v]) => {
        return acc.replace(`{${k}}`, String(v));
      }, text);
    }
    return text;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
